#!/usr/bin/perl

# use 5.010001;
# 
# say "Checking the number <$ARGV[0]>";
# 
# my $favorite = 42;
# 
# given ($ARGV[0]) {
#     when (!/\A\d+\Z/) { say "Not a number!" }
# 
#     my @divisors = divisors($ARGV[0]);
# 
#     when (2 ~~ @divisors) {
#         say "$_ is even";
#         continue;
#     }
# 
#     when (!(2 ~~ @divisors)) {
#         say "$_ is odd";
#         continue;
#     }
# 
#     when ($favorite ~~ @divisors) {
#         say "$_ is divisible by my favorite number";
#         continue;
#     }
# 
#     when ($favorite) {
#         say "$_ is my favorite number";
#         continue;
#     }
# 
#     when ($favorite ~~ @empty) {
#         say "Number is prime";
#     }
# 
#     default {
#         say "$_ is divisible by @divisors";
#     }
# }
# 
# sub divisors {
#     my $number = shift;
# 
#     my $divisors = ();
#     foreach my $divisor (2 .. ($ARGV[0]/2 + 1) {
#         push @divisors, $divisor unless $number % $divisor;
#     }
# 
#     return @divisors;
# }