#!/usr/bin/perl

use File::Basename;
use File::Spec;

my $source = $ARGV[0];
my $destination = $ARGV[1];
$destination = File::Spec->catfile($destination, basename $source) if -d $destination;
link $source, $destination or die "can't link from '$source' to '$destination': $!\n";