#!/usr/bin/perl

my %last_name = qw{
    fred flintstone Wilma Flintstone Barney Rubble
    betty rubble Bamm-Bamm Rubble PEBBLES FLINTSTONE
};

my @names = sort {
    lc($last_name{$a}) cmp lc($last_name{$b})
        or
    lc($a) cmp lc($b)
} keys %last_name;

foreach (@names) {
    printf "$last_name{$_} $_\n";
}