#!/usr/bin/perl

chomp(my @strings = <>);
while (1) {
    print 'Please enter a pattern: ';
    chomp(my $pattern = <STDIN>);

    last if $pattern =~ /^\s*$/;

    my @matches = eval {
        grep /$pattern/, @strings;
    };
    if ($@) {
        print "Error: $@";
    } else {
        my $count = @matches;
        print "There were $count matching strings:\n",
            "----------\n",
            map "$_\n", @matches,
            "----------";
    }
}