#!/usr/bin/perl

sub total {
    my $sum = 0;
    foreach (@_) {
        $sum += $_;
    }
    return $sum;
}

my @from_1_to_1000 = 1 .. 1000;
my $from_1_to_1000_total = &total(@from_1_to_1000);
print "The total of \@from_1_to_1000 is $from_1_to_1000_total.\n";