#!/usr/bin/perl

print "input length: ";
chomp($length = <STDIN>);

print "input words: \n";
chomp(@lines = <STDIN>);

print "1234567890" x (($length + 9) / 10), "\n";

foreach (@lines) {
    printf "%${length}s\n", $_;
}