#!/usr/bin/perl

my $match = '\Aabc\z';

my @lines;

chomp(@lines = <>);

foreach (@lines) {
    if (/$match/) {
        print "matched: |$`<$&>$'|\n";
    } else {
        print "no match: |$_|\n";
    }
} 